### ISSUE TITLE
Purpose of calculating state root of Starknet state

### ISSUE THREAD

**Issue by NIC619** [eqlabs/pathfinder#1163]
Hi, I saw in the [Features section](https://github.com/eqlabs/pathfinder#features) where it says:

> - verifies state using Ethereum
>     - calculates the Starknet state's Patricia-Merkle Trie root on a block-by-block basis and confirms it against L1

What's the reason to calculate and compare the state root instead of just trusting the state root and state diff that are verified by STARK proof?
Is there a fallback mechanism or a mechanism to alert light clients in the network or even the community when a state root is found to mismatch the one verified by STARK proof?

**Comment by Mirko-von-Leipzig** [comment]
> What's the reason to calculate and compare the state root instead of just trusting the state root and state diff that are verified by STARK proof?

We have no access to the stark proof so from our current perspective there is no way of knowing that such a proof has even been done. The only way we can know is once the L1 contract accepts the proof and updates its state.

We also want to trust as little as possible.

> Is there a fallback mechanism or a mechanism to alert light clients in the network or even the community when a state root is found to mismatch the one verified by STARK proof?

Currently, given the centralized nature of starknet, the only thing that changes is that data won't be marked as L1 accepted, but will remain L2 accepted. This is because there is no other L2 data source so there is nothing much else we can do.

> Is there a fallback mechanism or a mechanism to alert light clients in the network

We don't have anything to do with light clients - we just provide data according to the RPC specification. The light client will have to decide on what trade-off it wants to make ito security. Does it wait for data to be L1 accepted? Is L2 good enough? It's a latency / security trade-off.

**Comment by Mirko-von-Leipzig** [comment]
There was some more discussion [here](https://github.com/eqlabs/pathfinder/discussions/1126)

**Comment by NIC619** [comment]
> We have no access to the stark proof so from our current perspective there is no way of knowing that such a proof has even been done. The only way we can know is once the L1 contract accepts the proof and updates its state.

Thanks. I misunderstood that this process of "calculating and comparing state root" is done for verified blocks on L1. So that's why I was wondering why do you need to calculate and compare state root again as the block is already verified by STARK proof on L1. But now I realize this process is actually done for blocks received from p2p and it makes perfect sense. 

In the future there would likely be an accompanied STARK proof for block received from p2p? So that all full nodes don't have to execute transactions in the block again to verify.

**Comment by Mirko-von-Leipzig** [comment]
> In the future there would likely be an accompanied STARK proof for block received from p2p? So that all full nodes don't have to execute transactions in the block again to verify. Especially if the blocks are getting bigger and bigger.

Yes exactly! Once there is p2p and consensus with multiple sequencers and provers, full nodes that don't actively participate will have a few options. A starknet block will go through the following states:

1. published via consensus
2. proof published p2p
3. proof accepted on L1

At state (1) a full node can listen to consensus and follow the staker pools etc to gain some confidence in the block. If one wants to increase security even further one can also re-execute the block - but of course that now becomes expensive..
