### ISSUE TITLE
Remove unused configuration items

### ISSUE THREAD

**Issue by pierre-l** [eqlabs/pathfinder#1548]
Testnet2 was discontinued. Alchemy nodes have already stopped responding.

**Comment by Mirko-von-Leipzig** [comment]
Hmm we actually have some more deprecated config items. We should remove those as well since removing things is a breaking change.

```
--poll-pending
--python-subprocesses
```

These are accepted but do nothing now.

**Comment by pierre-l** [comment]
Will do

**Comment by Mirko-von-Leipzig** [comment]
Could also be good to align the configuration options properly.

There are a bunch of RPC related options that don't follow the `rpc.xxx` format e.g. `--max-rpc-connections`. Would be great to align those as well.

Its probably possible to semi-automate this `rpc` prefix but I think you would have to use the manual clap builder instead of derive. Probably best to leave that refactor to a issue / PR.
