### ISSUE TITLE
pathfinder v0.11.0-rc0 database size

### ISSUE THREAD

**Issue by Infer114** [eqlabs/pathfinder#1799]
was near the end of free space on my drive, 15gb remaining, and database was arround 860gb.
(for some context I used the snapshot in the past)
So I decided to install v0.11.0-rc0, and try the rework of the database => changed absolutely nothing in my case, exactly the same size.

Someone on discord (tomynocker) who just used the snapshot + regular sync till end => 200gb less !

I'm currently doing a fresh sync from scratch, without any snapshot downloaded to see the difference, will update the difference once it's done, but just for some teasing currently I'm near block 200k for 260Gb, so I expect a database size even lower !

**Comment by Mirko-von-Leipzig** [comment]
What occurs is that the database engine doesn't actually free up the space automatically. i.e. the database file remains the same size as before; but actually internally marks the data as deleted.

The database engine will likely re-use this now "empty" space when possible, so your future growth would be slower than poeple using < v0.10.x.

In order to fully gain back the space one has to run a `vacuum` process, which essentially "defragments" the database file to reclaim the deleted space. However, this process is extremely slow on databases of this size - as in many hours. So we chose not to automatically do this. If you're feeling adventurous you could run it manually yourself.

The snapshot we provided was a fresh resync, so it doesn't have this fragmentation issue.

**Comment by Mirko-von-Leipzig** [comment]
We are also working on a more permanent solution as well, which should see the database size drop to 25% of what it is currently.

**Comment by Infer114** [comment]
ok, thanks for your reply !
Can't try the `vacuum`, I deleted it for a fresh full sync, I was totally lacking of space !
If you are interested with a fresh new full sync 11.0-rc0 tell me, I can try to upload it somewhere once it's done, in few days in my case !

**Comment by Infer114** [comment]
something that could be cool, some kind of checkpoint sync, or similar things, like on ethereum ! 
No idea if this is possible, but just submitting it as an idea !

**Comment by Infer114** [comment]
database after a full resync post 0.11.0 is 690Gb for me !
If you want me to upload it somewhere tell me !
You can close this ticket for now if you want, I get 170Gb back, sounds good for a while now !

**Comment by Mirko-von-Leipzig** [comment]
> database after a full resync post 0.11.0 is 690Gb for me ! If you want me to upload it somewhere tell me ! You can close this ticket for now if you want, I get 170Gb back, sounds good for a while now !

Thanks, appreciate the offer; we've updated our snapshots links with more updated ones. Unfortunately we wouldn't be able to accept external snapshots - that would be unsafe, since technically you could tamper with the data 😁
