### ISSUE TITLE
`v05::method::get_transaction_status::tests::rejected` is flaky

### ISSUE THREAD

**Issue by sistemd** [eqlabs/pathfinder#1860]
On my PC, on latest main, when I do
```
cd crates/rpc
cargo t v05
```
Sometimes I get:
```
failures:

---- v05::method::get_transaction_status::tests::rejected stdout ----
thread 'v05::method::get_transaction_status::tests::rejected' panicked at crates/rpc/src/v05/method/get_transaction_status.rs
:236:67:
called `Result::unwrap()` on an `Err` value: TxnHashNotFound
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    v05::method::get_transaction_status::tests::rejected

test result: FAILED. 73 passed; 1 failed; 0 ignored; 0 measured; 378 filtered out; finished in 5.98s
```
CI for this code continues to pass.

It's worth nothing that sometimes this test fails even when run in isolation. E.g. in zsh:
```
while cargo t v05::method::get_transaction_status::tests::rejected; do; done
```
This loop eventually fails for me.

**Comment by Mirko-von-Leipzig** [comment]
We don't have rejected txns available locally, since those never make it into a block and therefore the node never sees it.

We therefore query the gateway for it; however we currently rather simplistically map all gateway errors to `TxnHashNotFound`. This is incorrect and we should only map the gateway equivalent error to this, and the rest to some custom variant.

What is likely happening in the loop is that you are getting rate-limited and we map this gateway error to `TxnHashNotFound`.
