### ISSUE TITLE
Can not start with Ganache:    Unsupported chain ID: 1337

### ISSUE THREAD

**Issue by EgoInc** [eqlabs/pathfinder#225]
So I wanna start StarkNet locally. I've started Ganache and compiled pathfinder.  I'm trying to launch it with  the next command:
```cargo run --release --bin pathfinder -- --ethereum.url http://172.21.160.1:7547```

Yet I get an error:
``` 
    Finished release [optimized] target(s) in 0.10s
     Running `/home/panda/pathfinder/target/release/pathfinder --ethereum.url 'http://172.21.160.1:7546'`
2022-04-02T09:43:59.442841Z  INFO 🏁 Starting node.
Error: Determining Ethereum chain

Caused by:
    Unsupported chain ID: 1337
```

I think that the problem may be related to the[ following lines](https://github.com/eqlabs/pathfinder/blob/d0ca729aa67b36ea2a9476c7a466e28f7ebbf08f/crates/pathfinder/src/ethereum.rs#L151). Could you please provide a Ganache compatible fix and/or tutorial what has to be changed in order for starknet to work on Ganache and explain why it does not currently work out of the box?

**Comment by Mirko-von-Leipzig** [comment]
Hi, sorry for the delayed response.

Currently we only support Ethereum chains which are supported by StarkNet. Which currently is `mainnet` and `goerlie`. Effectively, StarkNet has a lot of supporting infrastructure that is required by both StarkNet itself, as well as our `pathfinder` node in order to operate. StarkWare currently supplies all of this infrastructure but only on `mainnet` and `goerlie`.

It currently isn't very feasible (probably impossible?) to run your own local StarkNet as not all of the required parts are publically available.

We've chosen to simply hardcode these infrastructure points and addresses for now, as this requires a lot less configuration (and a lot less to mess up).
