### ISSUE TITLE
PATHFINDER_ETHEREUM_API_URL is not supported in latest docker image from dockerhub

### ISSUE THREAD

**Issue by jasonyic** [eqlabs/pathfinder#237]
PATHFINDER_ETHEREUM_API_URL is not recognised when using with the latest image `eqlabs/pathfinder` from dockerhub. image build from source DOES work as expected.

running by using eqlabs/pathfinder
```
docker run --rm -it -p 9545:9545 -e RUST_LOG=info -e PATHFINDER_ETHEREUM_API_URL="https://goerli.infura.io/v3/<PROJECT ID>" eqlabs/pathfinder
Error: Parsing configuration

Caused by:
    Ethereum HTTP URL is a required parameter
failed to resize tty, using default size
```

**Comment by Mirko-von-Leipzig** [comment]
This is expected -- maybe `latest` as the docker image name is a bit misleading. 

The `latest` docker image is not the latest main commit, but rather the `latest` release build. i.e. `latest` is equivalent to `v0.1.8-alpha` at this point in time. This is done to make it easier for users to pull the latest release using scripts.

We don't want to upload the latest `main` as an image because:
- its not always in a working state
- we need to be careful about what we release -- using a non-release could corrupt the database for example
- docker github flow currently takes 4hrs+ because its using QEMU to build some of the images for ARM :(

**Comment by Mirko-von-Leipzig** [comment]
At the time you raised the issue, latest was `0.1.7-alpha`, but we released `0.1.8-alpha` yesterday which does now include support these ENV variables.

**Comment by jasonyic** [comment]
@Mirko-von-Leipzig  thanks for the quick update and more understanding on the flow now. IMHO, a few indication in the release note and readme would be nice. thank you.

**Comment by Mirko-von-Leipzig** [comment]
Related issue #242.
