### ISSUE TITLE
Improve L2 errors

### ISSUE THREAD

**Issue by Mirko-von-Leipzig** [eqlabs/pathfinder#246]
We should be more thoughtful in how we handle L2 errors. Our current handling:
1. backoff and retry `N` times on transient connectivity errors, 
2. otherwise log the error, and then
3. restart the L2 sync processs

This can lead to issues where we are very spammy if we hit (2) as the process is simply restarted.

We should design a more robust system, where we are more precise in which errors we handle, retry or are fatal on.

**Comment by CHr15F0x** [comment]
We can distinguish two categories of errors based on their severity:
- "simple" transients, like for example rate limiting (HTTP 429) or timeouts,
- heavier errors, which can stem from:
    - temporary service unavailability/performance issues (HTTP 404, 503, etc.)
    - API upgrade or bug (usually manifesting in  a deserialization error).

While the former type should trigger a retry the latter should also trigger a retry, albeit maybe with a longer backoff time, as it is impossible to distinguish bugs or temporary failures from permanent changes like API upgrades just by looking at the API reply without actually consulting the service provider in the first place. So by assuming that an error from the second group also can potentially be temporary we allow the node to recover just by leaving the retry logic to do its job. However due to the severity of the latter type of errors these should at least be logged in a much more explicit and visible way.

Errors can also be divided based on if they impact all or one particular query, for example:
- an HTTP 404 impacts all queries,
- an API upgrade impacts only the upgraded queries.

This means that an indication of the former type of error for one query should trigger automatic backoff for all other queries that would normally be sent during the backoff period.

The following table contains various types of errors

**Comment by CHr15F0x** [comment]
Fixed in #257 .
