### ISSUE TITLE
Push API for events

### ISSUE THREAD

**Issue by tdelabro** [eqlabs/pathfinder#263]
Hello,

It seems that the node only offers events through pulling. It's not really convenient for front end application.
Is it planned to implement a push mechanism to get events from a node ?
Would you be keen for an external contribution on this subject ?

**Comment by Mirko-von-Leipzig** [comment]
Hi, sorry for the delayed feedback.

Are you referring to a subscription based function? Using WebSockets? Or what did you have in mind?

**Comment by tdelabro** [comment]
Hi Mirko,

Yeah that's more or less it.
I would like my front to subscribe to a websocket for a specific contract and have related events being pushed to it when they occur.

**Comment by Mirko-von-Leipzig** [comment]
This is something we want to support in the future, but is sort of medium term on our list of priorities currently.

While in general we are keen for external contributions, we feel like this one will be difficult to get across the line because it needs to be
- cognisant of this API as a DoS attack vector
- account for our upcoming p2p plans (which are themselves not yet fully fleshed out)
- RPC API approved by StarkWare for support by other possible node

If you're still keen to give it a go, we can provide some guidance but our attention will mostly be elsewhere in the short term.
