### ISSUE TITLE
Confusing (lack of) logs when the wrong Ethereum node url is provided

### ISSUE THREAD

**Issue by fracek** [eqlabs/pathfinder#374]
When the Ethereum node provided is not valid, pathfinder will not output any type of warning or informational message, instead it will simply retry to connect forever.

My advice is to output some type of warning or error message so that as an operator I can setup Grafana to monitor for these messages and alert me if pathfinder cannot connect to geth.

I can fix this in a PR but wanted to know your opinion before I write any code.

**Comment by Mirko-von-Leipzig** [comment]
It appears we currently only log transport errors under `debug` log level. The reason this was done like this is because non-technical users end up flooding our support systems whenever there is downtime in the network.

This isn't a great solution so we should revisit this; but I also don't have an idea on how to resolve this correctly. 

Note that providing an invalid url is indistinguishable from there being network issues or the node being temporarily unavailable so its not like we can make a hard decision here.

**Comment by koivunej** [comment]
I think this was fixed in #423, could you @fracek verify? This is already in v0.2.4-alpha.

**Comment by koivunej** [comment]
Well, #423 didn't really fix this ... Maybe the #194 will help with this, you could be able to detect that pathfinder has been stuck for a long time in startup.

**Comment by CHr15F0x** [comment]
As of `0.3.7`, when providing an invalid url, I get:
```
Error: Determine Ethereum chain.

Hint: Make sure the provided ethereum.url and ethereum.password are good.

Caused by:
    code 401
```
which is sufficient to close the issue as fixed.
