### ISSUE TITLE
Sequencer client spews large error message for internal server error

### ISSUE THREAD

**Issue by Mirko-von-Leipzig** [eqlabs/pathfinder#453]
The Sequencer client does not handle error `500 - Internal server error` very well. The process is correct, however it emits a large error message for it.

I suggest that we both
1. add in error 500, and
2. replace the explicit error list with `unknown error variant` instead

```
2022-07-13T14:48:15.751964Z ERROR block: Request failed, retrying reason=error decoding response body: unknown variant `500`, 
expected one of `StarknetErrorCode.BLOCK_NOT_FOUND`, `StarknetErrorCode.ENTRY_POINT_NOT_FOUND_IN_CONTRACT`, 
`StarknetErrorCode.OUT_OF_RANGE_CONTRACT_ADDRESS`, `StarknetErrorCode.OUT_OF_RANGE_CONTRACT_STORAGE_KEY`, 
`StarkErrorCode.SCHEMA_VALIDATION_ERROR`, `StarknetErrorCode.TRANSACTION_FAILED`, 
`StarknetErrorCode.UNINITIALIZED_CONTRACT`, `StarknetErrorCode.OUT_OF_RANGE_BLOCK_HASH`, 
`StarknetErrorCode.OUT_OF_RANGE_TRANSACTION_HASH`, `StarkErrorCode.MALFORMED_REQUEST`, 
`StarknetErrorCode.UNSUPPORTED_SELECTOR_FOR_FEE`, `StarknetErrorCode.INVALID_CONTRACT_DEFINITION`, 
`StarknetErrorCode.NON_PERMITTED_CONTRACT`, `StarknetErrorCode.UNDECLARED_CLASS` at line 1 column 14 
block=Number(StarknetBlockNumber(33443))
```

**Comment by koivunej** [comment]
The 500 response in question had also a json body `{"code": "500", "message": "Internal server error"}`. Didn't check if it had correct content-type.

**Comment by CHr15F0x** [comment]
Depending on what the reply body carries, the decode errors can vary, for example: `error decoding response body: expected value at line 1 column 1` when it's just "some string".
The very first error mentioned in this issue:
>2022-07-13T14:48:15.751964Z ERROR block: Request failed, retrying reason=error decoding response body: unknown variant `500`, 
expected one of `StarknetErrorCode.BLOCK_NOT_FOUND`, `StarknetErrorCode.ENTRY_POINT_NOT_FOUND_IN_CONTRACT`, 
`StarknetErrorCode.OUT_OF_RANGE_CONTRACT_ADDRESS`, `StarknetErrorCode.OUT_OF_RANGE_CONTRACT_STORAGE_KEY`, 
`StarkErrorCode.SCHEMA_VALIDATION_ERROR`, `StarknetErrorCode.TRANSACTION_FAILED`, 
`StarknetErrorCode.UNINITIALIZED_CONTRACT`, `StarknetErrorCode.OUT_OF_RANGE_BLOCK_HASH`, 
`StarknetErrorCode.OUT_OF_RANGE_TRANSACTION_HASH`, `StarkErrorCode.MALFORMED_REQUEST`, 
`StarknetErrorCode.UNSUPPORTED_SELECTOR_FOR_FEE`, `StarknetErrorCode.INVALID_CONTRACT_DEFINITION`, 
`StarknetErrorCode.NON_PERMITTED_CONTRACT`, `StarknetErrorCode.UNDECLARED_CLASS` at line 1 column 14 
block=Number(StarknetBlockNumber(33443))

happens to be pretty informative, because even though the variant of one field is invalid, the schema of the reply is followed regardless.
I'd return `Unknown error variant` in any case, ie: body decoding failed or even when body fetching failed.
