### ISSUE TITLE
Felt representation in response object doesn't comply with the spec.

### ISSUE THREAD

**Issue by eschnou** [eqlabs/pathfinder#674]
The JSRPC spec mandates the following regex for felt representation: `^0x0[a-fA-F0-9]{1,63}$` - but the API currently returns strings without the leading zero, causing confusion for downstream services attempting to index/lookup this data.
https://github.com/starkware-libs/starknet-specs/blob/master/api/starknet_api_openrpc.json#L937

In addition, the current JSPRC is ambiguous since it can lead to different representations of the same address. It would be great if pathfinder could standardize on a single canonical representation of felts and document it. Two potential ideas:
- always be 63 digits (using zero padding if needed) : ^0x0[a-fA-F0-9]{63}$
- always be the shortest string: ^0x0[a-fA-F1-9]{1}[a-fA-F0-9]{0,62}$

I assume that the current implicit behavior is always to have the shortest string and you just need to add the leading zero to be compliant with the spec?

**Comment by CHr15F0x** [comment]
I reached out to Starkware, because the current description of felt does not seem to convey their full intentions, for example:
- the single leading zero after the `0x` prefix in the regexp `^0x0` could suggest an even hex digit padding, but honestly looking at the entire regexp _any_ number of leading zeros is valid, as long as the string contains between 2 and 64 hex digits.

I assume the description should be more specific wrt:
- removing leading 0s,
- padding with a 0 to achieve an even number of digits,
- or explicitly removing _all_ leading zeros even if the result contains an odd number of digits, with the sole exception of a zero felt (which would then be represented as `0x0`).

Otherwise the issue of not properly following the spec wrt felt representation is going to be a recurring problem.

**Comment by CHr15F0x** [comment]
There is a spec [PR](https://github.com/starkware-libs/starknet-specs/pull/58) that solves this issue. Once it's merged into the spec we'll implement it. The ambiguity will be gone and pathfinder will comply with the spec in this respect :sweat_smile: .

**Comment by sergey-melnychuk** [comment]
Closing as solved.
