### ISSUE TITLE
start has error,what reason?

### ISSUE THREAD

**Issue by popeye2022** [eqlabs/pathfinder#715]
i follow this document : https://mirror.xyz/dzupp.eth/8HfjYCkbid2vlayxyPtSD9_wtb9a-wHb1uOENsAOwng

Caused by:
    0: Sequencer transport error: error decoding response body: unknown field `gas_price`, expected one of `block_hash`, `block_number`, `parent_block_hash`, `state_root`, `status`, `timestamp`, `transaction_receipts`, `transactions` at line 1 column 252
    1: error decoding response body: unknown field `gas_price`, expected one of `block_hash`, `block_number`, `parent_block_hash`, `state_root`, `status`, `timestamp`, `transaction_receipts`, `transactions` at line 1 column 252
    2: unknown field `gas_price`, expected one of `block_hash`, `block_number`, `parent_block_hash`, `state_root`, `status`, `timestamp`, `transaction_receipts`, `transactions` at line 1 column 252

<img width="1323" alt="image" src="https://user-images.githubusercontent.com/112548587/200506509-710c6ac1-0cfd-41e2-879c-26c051835708.png">

**Comment by Mirko-von-Leipzig** [comment]
The guide is pretty outdated (it is not written by us). In this part:

> Create a local copy of pathfinder’s github repository by typing:
> 
> git clone --branch v0.1.2-alpha https://github.com/eqlabs/pathfinder.git
> 
> Replace v0.1.3-alpha with newer version if that exists. You check that by visiting [pathfinder’s repo](https://github.com/eqlabs/pathfinder/tags).

You must replace the `v0.1.2-alpha` with the latest pathfinder version. Which currently is `v0.3.8`. So use:
```
git clone --branch v0.3.8 https://github.com/eqlabs/pathfinder.git
```

However, we would recommend using our docker images instead of our raw source code. It is much easier to maintain for non-programmers.

There is a small guide on how to run the pathfinder node using docker in our readme [here](https://github.com/eqlabs/pathfinder#running-with-docker).
