### ISSUE TITLE
Locking issue when reading data

### ISSUE THREAD

**Issue by lazarmitic** [eqlabs/pathfinder#737]
There seems to be some kind of locking issue in Pathfinder, when I start a transaction (for example mint), while that mint tx is in pending state on mainnet, I can't read totalSupply() for that same token (tx fails), it seems like mint tx locks totalSupply storage value, and I can't read it while tx that is modifying that value is pending. I'm not sure if this is caused because Infura is using v0.4.0 pathfinder that is updated to cairo v0.10.2 and mainnet is still on v0.10.1, or something else. I tested same thing with sequencer and everything is working properly.

**Comment by Mirko-von-Leipzig** [comment]
I'm not entirely following so just some questions to try understand.

1. You're using Infura's starknet RPC API? Or is it some built-in Infura website thing like metamask with a UI and buttons? (I'm not very familiar with how Infura presents these things).
2. How do you know the mint tx is pending? By using the RPC API with `pending`?
3. How do you read `totalSupply()`? Is it a `starknet_call` using the RPC API?
4. Can you provide the tx failure error?

**Comment by lazarmitic** [comment]
1. I'm using Infura RPC to read data from the chain.
2. I use StarkScan to follow the state of the transaction.
3. I'm using Starknet.js to invoke contract function, and yes, I guess under the hook Starknet.js uses `starknet_call` method.
4. Error I get is not really descriptive, but here it is `Error: -32603: Internal error: StarknetErrorCode.TRANSACTION_FAILED`.

More info:
https://starkscan.co/tx/0x68ac5959c5daea2b09b51123e806db8c37141c14de8c698473b9abd9b0b8b7 - this is mint tx.
https://starkscan.co/contract/0x070f8a4fcd75190661ca09a7300b7c93fab93971b67ea712c664d7948a8a54c6 - this is token contract for which totalSupply() fails to load.

**Comment by lazarmitic** [comment]
Just one more thing, I first suspected that problem is with Infura, so I tried other RPC provider `Chainstack` and they have same problem, both of these providers use Pathfinder 0.4.0.

**Comment by Mirko-von-Leipzig** [comment]
Thanks that all makes sense.

Ah damn, I was hoping the error message would be more informative.

There should be exactly one major difference with pathfinder 0.4.0 and that is for fee estimation. It is using the cost which is aligned with starknet 0.10.2. However this should only be impacting `starknet_estimateFee`. But it does not sound like that should impact you at all since you're using `starknet_call` under the hood.

The only other difference is that we are also using the newer cairo-vm to execute `starknet_call` - but afaik it should be equivalent to starknet 0.10.1 cairo-vm in execution at least.

We'll have to investigate what exactly is causing the transaction to fail.

**Comment by Mirko-von-Leipzig** [comment]
@lazarmitic can you confirm that `totalSupply()` succeeds once the mint transaction is no longer pending and has formed part of a complete block?

We're running the query locally and of course its working now. But that's because we can't really force the pending transaction to be present.

**Comment by lazarmitic** [comment]
Yes, currently it's working, it does not work only if mint transaction is pending.

**Comment by lazarmitic** [comment]
We can try to synchronize. I can execute new mint transaction and you can monitor read functionality for list of tokens I can provide.

**Comment by Mirko-von-Leipzig** [comment]
> We can try to synchronize. I can execute new mint transaction and you can monitor read functionality for list of tokens I can provide.

I think we're okay without it for now. We've identified that's its definitely something with pathfinder and pending.

The call works for `latest` but always fails for `pending` -- regardless of whether your mint transaction is pending or not. I suspect the reason it seems connected is because your SDK is automatically choosing pending or latest depending on that transactions state?

i.e.: This always fails:
```bash
curl -s --json '{
    "jsonrpc": "2.0",
    "method": "starknet_call",
    "params": [
        {
            "contract_address": "0x070f8a4fcd75190661ca09a7300b7c93fab93971b67ea712c664d7948a8a54c6",
            "entry_point_selector": "0x80aa9fdbfaf9615e4afc7f5f722e265daca5ccc655360fa5ccacf9c267936d",
            "calldata": []
        },
        "pending"
    ],
    "id": 1
}
' <rpc-url> | jq
```

The only difference would be with how we setup our pending data somehow, and pass it to the cairo-vm.

Thanks! We can replicate this locally now. Will get back to you once we've fixed / figured it out.

**Comment by lazarmitic** [comment]
Thanks!

**Comment by kkovaacs** [comment]
It might be that we'd still need that pending `mint` transaction to diagnose this further. Can we somehow synchronize so that we can catch your transaction still in pending?

**Comment by kkovaacs** [comment]
So, with the help of @lazarmitic we've been able to dig further into the issue.

This is the mint transaction: https://starkscan.co/tx/0x3c00fd81ca2416e783bc47cff4863ed6c7e904d51886fca90121f733646bce7

We've observed the following:

- Pathfinder periodically updates the pending block from the gateway. As soon as the transaction above made it into pathfinder's pending block the `starknet_call` to `totalSupply` of contract 0x070f8a4fcd75190661ca09a7300b7c93fab93971b67ea712c664d7948a8a54c6 started failing.
- Once the pending block has made it onto the chain (so the transaction above was L2_ACCEPTED) the same `starknet_call` call started working again.

The exact same issue can be reproduced by the following command (and a sufficiently up-to-date mainnet database containing block 11486):

```python
    c = Call(
        at_block="0x74cc50f4b8083835682bbe1489a4b1474053e4f6a35c66b8bb25b2e700630f9",
        chain=call.Chain.MAINNET,
        pending_updates={
            0x3D39F7248FB2BFB960275746470F7FB470317350AD8656249EC66067559E892: [
                call.StorageDiff(
                    key=0x57E3AC4C831E9CE78DE8142D212350256E7263262456048615D1800F91A021,
                    value=0xDE21C10E8E2457F,
                ),
                call.StorageDiff(
                    key=0x41FB32DAA5E26566D482776D5F8ABFF389DA500038A86A288F5ADB39276AD55,
                    value=0x27FC7A436ABEEE,
                ),
                call.StorageDiff(
                    key=0x5A827682859FAFF64442160965F441FC4344F998E6818244814B04A830749EA,
                    value=0x6380C4AD,
                ),
                call.StorageDiff(
                    key=0x69010E0D78ABB0652354B78994622E24A9E47A8D30D5C4C0C9FB2DF3DBC04CF,
                    value=0xDE2B4696C7152F6,
                ),
                call.StorageDiff(
                    key=0x747A639BB6DBAE6D3A00A22E5E976EB21F6A8C0D87B25A9E77C50759D7066CB,
                    value=0x9737843489E05,
                ),
            ],
        },
        pending_deployed=[],
        pending_nonces={},
        contract_address=3193647238523375300127598243000966435117811015280340811133237455989949224134,
        calldata=[],
        entry_point_selector=227334030968744315992796982100494617316223563777432855541120004521101595501,
        gas_price=0,
    )
```

The state update data above is the minimal subset of the state update for the pending block that still triggers this issue.

The exception we get is:
```
E           starkware.starkware_utils.error_handling.StarkException: (500, {'code': <StarknetErrorCode.TRANSACTION_FAILED: 44>, 'message': 'Error at pc=0:128:\nGot an exception while executing a hint.\nCairo traceback (most recent call last):\nUnknown location (pc=0:3188)\nUnknown location (pc=0:3171)\nUnknown location (pc=0:2163)\nUnknown location (pc=0:992)\n\nError in the called contract (0x70f8a4fcd75190661ca09a7300b7c93fab93971b67ea712c664d7948a8a54c6):\nError at pc=0:128:\nGot an exception while executing a hint.\nCairo traceback (most recent call last):\nUnknown location (pc=0:3409)\nUnknown location (pc=0:3387)\nUnknown location (pc=0:520)\n\nError in the called contract (0x3d39f7248fb2bfb960275746470f7fb470317350ad8656249ec66067559e892):\nError message: SafeUint256: subtraction overflow\nError at pc=0:527:\nAn ASSERT_EQ instruction failed: 0 != 1.\nCairo traceback (most recent call last):\nUnknown location (pc=0:3354)\nUnknown location (pc=0:3330)\nUnknown location (pc=0:908)'})
```

The interesting part from the exception above is:
```Error in the called contract (0x3d39f7248fb2bfb960275746470f7fb470317350ad8656249ec66067559e892):\nError message: SafeUint256: subtraction overflow```

Initially I thought this might maybe be some state in the pending block triggering the overflow. Then I tried to do the following experiment: since we know that the same call works OK for block 11487 (the one having the mint transaction applied) I just took the state update from block 11487 and used that as the pending state update on top of block 11486. This should have caused an equivalent behavior (compared to running the call on 11487) since the resulting state the call is executed on should be the same. Unfortunately the call to the contract above still fails with the complete state update from the next block applied.

This behavior seems to suggest we have some problems when we're applying state updates from the pending block.
